### ISSUE TITLE
通过ui:options传值为function的参数，不能传递到xformUploadWidget组件内部？

### ISSUE THREAD

**Issue by kikijiang** [alibaba/scalable-form-platform#2]
通过ui:options给xformUploadWidget组件传beforeUpload参数失败，但是换作其他类型的值就可以。这是什么情况，怎么传递自定义的beforeUpload方法？
<img width="1129" alt="WechatIMG30" src="https://user-images.githubusercontent.com/19896985/80899128-dc326380-8d3e-11ea-8f14-eb02e36f6414.png">

**Comment by kikijiang** [comment]
貌似发现问题了，scalable-form-core/src/index.js中通过deepCloneObject对uiSchema进行了深拷贝处理，但是JSON.parse(JSON.stringify(obj))不能处理值为function的对象，因此过滤掉了所有值为function的参数。
![企业微信截图_1cd3c485-3212-4a22-9054-0338579af4c2](https://user-images.githubusercontent.com/19896985/81143653-e6ee3200-8fa4-11ea-951c-f2b8271c5ab2.png)
以上是我的理解，请各路大神指点吖！

**Comment by lvshuncn** [comment]
可以使用formContext，传递公共方法到各个组件，每一个组件都可以获得formContext中的数据

**Comment by kikijiang** [comment]
> 可以使用formContext，传递公共方法到各个组件，每一个组件都可以获得formContext中的数据

一个表单中有多个select组件，分别需要不同的onSearch方法，这个场景就不能使用formContext传递了。
